version: "3"
services:
  pg-db:
    image: postgres
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}

  web:
    build: .

#    used bash for migrate and run.
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
    - "8000:8000"
    depends_on:
      - pg-db